=== euroargodev/sensor_metadata_json/schemas/argo.float.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "./argo.float.schema.json",
    "title": "JSON Schema for Argo Program float = platform + sensors",
    "description": "A JSON Schema used to describe an Argo float. A float consists of a single platform and any number of sensors.  See Argo User's Manual. Metada format Version 3.41.1",
    "format_version": {
        "const": "0.5.0"
    },
    "type": "object",
    "properties": {
        "float_info": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string",
                    "description": "The entity primarily responsible for making the content of this JSON metadata resource"
                },
                "date_creation": {
                    "type": "string",
                    "format": "date-time",
                    "description": "Date and time of creation of the resource.  RFC 3339 format compliant with ISO 8601"
                },
                "link": {
                    "const": "./argo.float.schema.json",
                    "description": "Link to JSON Schema that validates this JSON metadata resource"
                },
                "format_version": {
                    "$ref": "#/format_version",
                    "description": "Schema version for this resource. Must match /format_version."
                },
                "contents": {
                    "type": "string",
                    "description": "Description of this JSON metadata respirce."
                },
                "float_described": {
                    "type": "string",
                    "description": "Identification of float described by this JSON metadata resouce: Ideally: float-<PLATFORM_VENDOR>-<FLOAT_SERIAL_NUMBER>."
                }
            },
            "required": [
                "created_by",
                "date_creation",
                "link",
                "format_version",
                "contents",
                "float_described"
            ]
        }, 
        "@context": {
            "type": "object",
            "properties": {
                "SDN:R03::": { "const": "http://vocab.nerc.ac.uk/collection/R03/current/" },
                "SDN:R08::": { "const": "http://vocab.nerc.ac.uk/collection/R08/current/" },
                "SDN:R09::": { "const": "http://vocab.nerc.ac.uk/collection/R09/current/" },
                "SDN:R10::": { "const": "http://vocab.nerc.ac.uk/collection/R10/current/" },
                "SDN:R22::": { "const": "http://vocab.nerc.ac.uk/collection/R22/current/" },
                "SDN:R23::": { "const": "http://vocab.nerc.ac.uk/collection/R23/current/" },
                "SDN:R24::": { "const": "http://vocab.nerc.ac.uk/collection/R24/current/" },
                "SDN:R25::": { "const": "http://vocab.nerc.ac.uk/collection/R25/current/" },
                "SDN:R26::": { "const": "http://vocab.nerc.ac.uk/collection/R26/current/" },
                "SDN:R27::": { "const": "http://vocab.nerc.ac.uk/collection/R27/current/" },
                "SDN:R28::": { "const": "http://vocab.nerc.ac.uk/collection/R28/current/" }
            },
            "description": "Mapping from SDN NVS term IDs to validation URL.  Must be present in JSON float metadata resource.",
            "required": [
                "SDN:R03::",
                "SDN:R08::",
                "SDN:R09::",
                "SDN:R10::",                
                "SDN:R22::",
                "SDN:R23::",
                "SDN:R24::",
                "SDN:R25::",
                "SDN:R26::",
                "SDN:R27::",
                "SDN:R28::"
            ],
            "additionalProperties": false
        },
        "files_merged" : {
            "type" : "array",
            "items" : {
                "type" : "string"
            },
            "description": "Array of one platform JSON filename and multiple sensors JSON filename merged to create this JSON float metadata resource"
        },
        "platform_info" : { 
            "$ref": "./argo.platform.schema.json#/properties/platform_info",
            "description": "Schema-valid platform metadata instance, typically from JSON PLATFORM file"
        },
        "sensor_info_list" : {
            "type" : "array",
            "items" : {
                "$ref": "./argo.sensor.schema.json#/properties/sensor_info" 
            },
            "description": "Array of schema-valid sensor_info metadata instances, typically from JSON SENSOR files."

        },
        "PLATFORM" : { 
            "$ref": "./argo.platform.schema.json#/properties/PLATFORM",
            "description": "Schema-valid PLATFORM metadata instance, typically from JSON PLATFORM file."
        },
        "SENSORS" : { 
            "$ref": "./argo.sensor.schema.json#/properties/SENSORS",
            "description": "Array of schema-valid SENSOR metadata instances, typically from JSON SENSOR files."
        },
        "PARAMETERS" : { 
            "$ref" : "./argo.sensor.schema.json#/properties/PARAMETERS",
            "description": "Array of schema-valid PARAMETER metadata instances corresponding to SENSORS above.  Typically from JSON SENSOR files."
        }
    },
    "required": [
        "@context",
        "float_info",
        "files_merged",
        "platform_info",
        "sensor_info_list",
        "PLATFORM",
        "SENSORS",
        "PARAMETERS"
    ],
    "uniqueItems": true,
    "additionalProperties": false
}

=== euroargodev/sensor_metadata_json/json_floats/float-SBE-NAVIS_EBR-1101.json
{
  "float_info": {
    "created_by": "make_float_json_from_floatdef.m",
    "date_creation": "2024-03-20T08:38:15Z",
    "format_version": "0.5.0",
    "link": "./argo.float.schema.json",
    "contents": "json file to describe a platform with sensors for Argo",
    "float_described": "SBE-NAVIS_EBR-1101"
  },
  "files_merged": [
    "platform-SBE-NAVIS_EBR-1101.json",
    "sensor-RBR-RBR_ARGO3-205908.json",
    "sensor-SBE-SBE41CP-11643.json",
    "sensor-AANDERAA-AANDERAA_OPTODE_4330-3901.json"
  ],
  "@context": {
    "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
    "SDN:R08::": "http://vocab.nerc.ac.uk/collection/R08/current/",
    "SDN:R09::": "http://vocab.nerc.ac.uk/collection/R09/current/",
    "SDN:R10::": "http://vocab.nerc.ac.uk/collection/R10/current/",
    "SDN:R22::": "http://vocab.nerc.ac.uk/collection/R22/current/",
    "SDN:R23::": "http://vocab.nerc.ac.uk/collection/R23/current/",
    "SDN:R24::": "http://vocab.nerc.ac.uk/collection/R24/current/",
    "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
    "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
    "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/",
    "SDN:R28::": "http://vocab.nerc.ac.uk/collection/R28/current/"
  },
  "platform_info": {
    "created_by": "ECR",
    "date_creation": "2023-02-03T07:41:54-07:00",
    "link": "./argo.platform.schema.json",
    "format_version": "0.5.0",
    "contents": "json file to describe a NAVIS_EBR platform WMOID 6904191 platform for Argo",
    "platform_described": "SBE-NAVIS_EBR-1101"
  },
  "sensor_info_list": [
    {
      "created_by": "BAK test",
      "date_creation": "2023-02-03T07:38:07Z",
      "link": "./argo.sensor.schema.json",
      "format_version": "0.5.0",
      "contents": "json file to describe a sensor for Argo. v0.4.0 draft",
      "sensor_described": "RBR-RBR_ARGO3-205908"
    },
    {
      "created_by": "BAK test",
      "date_creation": "2023-02-03T07:38:07Z",
      "link": "./argo.sensor.schema.json",
      "format_version": "0.5.0",
      "contents": "json file to describe a sensor for Argo. v0.4.0 draft",
      "sensor_described": "SBE-SBE41CP-11643 on float 6904191"
    },
    {
      "created_by": "BAK test",
      "date_creation": "2023-02-03T07:38:07Z",
      "link": "./argo.sensor.schema.json",
      "format_version": "0.5.0",
      "contents": "json file to describe a sensor for Argo. v0.4.0 draft",
      "sensor_described": "AANDERAA-AANDERAA_OPTODE_4330-3901"
    }
  ],
  "PLATFORM": {
    "POSITIONING_SYSTEM": [
      "SDN:R09::GPS"
    ],
    "PTT": "1101i",
    "TRANS_SYSTEM": [
      "SDN:R10::IRIDIUM"
    ],
    "PLATFORM_FAMILY": "SDN:R22::FLOAT",
    "PLATFORM_TYPE": "SDN:R23::NAVIS_EBR",
    "PLATFORM_MAKER": "SDN:R24::SBE",
    "WMO_INST_TYPE": "SDN:R08::863",
    "FIRMWARE_VERSION": "BGCi_OPTOx_MCOM_SUNA_PH_ICE_EXP 210521",
    "MANUAL_VERSION": "",
    "FLOAT_SERIAL_NO": "1101",
    "BATTERY_TYPE": "ELECTROCHEM Lithium 15.0 V",
    "BATTERY_PACKS": "3DD Li",
    "CONTROLLER_BOARD_TYPE_PRIMARY": "SDN:R28::N1",
    "CONTROLLER_BOARD_SERIAL_NO_PRIMARY": "00000",
    "platform_vendorinfo": {
      "vendor_schema": "SBE",
      "version": "0.2",
      "SBE_manufacturing_date": "2014-07-17T00:00:00Z"
    }
  },
  "SENSORS": [
    {
      "SENSOR": "SDN:R25::CTD_PRES",
      "SENSOR_MAKER": "SDN:R26::RBR",
      "SENSOR_MODEL": "SDN:R27::RBR_PRES_A",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "205908",
      "sensor_vendorinfo": {
        "vendor_schema": "RBR",
        "version": "0.1",
        "RBR_foo1": 1,
        "RBR_foo2": "twotwo"
      }
    },
    {
      "SENSOR": "SDN:R25::CTD_TEMP",
      "SENSOR_MAKER": "SDN:R26::RBR",
      "SENSOR_MODEL": "SDN:R27::RBR_ARGO3",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "205908",
      "sensor_vendorinfo": {
        "vendor_schema": "None",
        "example": "Vendors can add their own sensor info here; they can add any field they like as a fieldname below sensor_vendorinfo"
      }
    },
    {
      "SENSOR": "SDN:R25::CTD_CNDC",
      "SENSOR_MAKER": "SDN:R26::RBR",
      "SENSOR_MODEL": "SDN:R27::RBR_ARGO3",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "205908",
      "sensor_vendorinfo": {
        "vendor_schema": "None",
        "example": "Vendors can add their own sensor info here; they can add any field they like as a fieldname below sensor_vendorinfo"
      }
    },
    {
      "SENSOR": "SDN:R25::CTD_TEMP_CNDC",
      "SENSOR_MAKER": "SDN:R26::RBR",
      "SENSOR_MODEL": "SDN:R27::RBR_ARGO3",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "205908",
      "sensor_vendorinfo": {
        "vendor_schema": "None",
        "example": "Vendors can add their own sensor info here; they can add any field they like as a fieldname below sensor_vendorinfo"
      }
    },
    {
      "SENSOR": "SDN:R25::CTD_PRES2",
      "SENSOR_MAKER": "SDN:R26::DRUCK",
      "SENSOR_MODEL": "SDN:R27::DRUCK_2900PSIA",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "11076214",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2022-01-01T00:00:00Z"
      }
    },
    {
      "SENSOR": "SDN:R25::CTD_TEMP2",
      "SENSOR_MAKER": "SDN:R26::SBE",
      "SENSOR_MODEL": "SDN:R27::SBE41CP",
      "SENSOR_SERIAL_NO": "11643",
      "SENSOR_FIRMWARE_VERSION": " ",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2022-01-01T00:00:00Z"
      }
    },
    {
      "SENSOR": "SDN:R25::CTD_CNDC2",
      "SENSOR_MAKER": "SDN:R26::SBE",
      "SENSOR_MODEL": "SDN:R27::SBE41CP",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "11643",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2022-01-01T00:00:00Z"
      }
    },
    {
      "SENSOR": "SDN:R25::OPTODE_DOXY",
      "SENSOR_MAKER": "SDN:R26::AANDERAA",
      "SENSOR_MODEL": "SDN:R27::AANDERAA_OPTODE_4330",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "3901"
    }
  ],
  "PARAMETERS": [
    {
      "PARAMETER": "SDN:R03::PRES",
      "PARAMETER_SENSOR": "SDN:R25::CTD_PRES",
      "PARAMETER_UNITS": "dbar",
      "PARAMETER_ACCURACY": "1",
      "PARAMETER_RESOLUTION": "0.02",
      "PREDEPLOYMENT_CALIB_EQUATION": "Pcorr = X0+(Pmeas-X0-X1*(Tpres-X5)-X2*(Tpres-X5)^2-X3*(Tpres-X5)^3)/(1+X4*(Tpres-X5)); Pmeas = C0+C1*VR+C2*VR^2+C3*VR^3;",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "C0": "-55.76767",
        "C1": "4.0054912E3",
        "C2": "-66.53745",
        "C3": "6.39357",
        "X0": "10.0361",
        "X1": "184.89905E-3",
        "X2": "330.90703E-6",
        "X3": "-999.3263E-9",
        "X4": "-86.53429E-6",
        "X5": "21.942171"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Pressure Calibration Date              2020-12-03",
      "PREDEPLOYMENT_CALIB_DATE": "2020-12-02T00:00:00Z",
      "parameter_vendorinfo": {
        "vendor_schema": "None",
        "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
      },
      "predeployment_vendorinfo": {
        "vendor_schema": "RBR",
        "version": "0.1",
        "certificate": "https://oem-lookup.rbr-global.com/api/v1/instruments/205908/channels/8/certificate"
      }
    },
    {
      "PARAMETER": "SDN:R03::TEMP",
      "PARAMETER_SENSOR": "SDN:R25::CTD_TEMP",
      "PARAMETER_UNITS": "degC (ITS-90)",
      "PARAMETER_ACCURACY": "0.002",
      "PARAMETER_RESOLUTION": "0.00005",
      "PREDEPLOYMENT_CALIB_EQUATION": "Temperature = 1/(C0+C1*ln(1/VR-1)+C2*ln(1/VR-1)^2+C3*ln(1/VR-1)^3)-273.15;",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "C0": "3.4669158E-3",
        "C1": "-249.6654E-6",
        "C2": "2.4878973E-6",
        "C3": "-60.271525E-9"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Temperature Calibration Date           2020-12-02",
      "PREDEPLOYMENT_CALIB_DATE": "2020-12-02T00:00:00Z",
      "parameter_vendorinfo": {
        "vendor_schema": "None",
        "example": "Vendors can add their own parameter info here; they can add any field they like as a fieldname below parameter_vendorinfo"
      },
      "predeployment_vendorinfo": {
        "vendor_schema": "None",
        "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
      }
    },
    {
      "PARAMETER": "SDN:R03::PSAL",
      "PARAMETER_SENSOR": "SDN:R25::CTD_CNDC",
      "PARAMETER_UNITS": "psu",
      "PARAMETER_ACCURACY": "0.003",
      "PARAMETER_RESOLUTION": "0.001",
      "PREDEPLOYMENT_CALIB_EQUATION": "Salinity = PSS-78 (Temperature, Ccorr, Hydrostatic Pressure); Ccorr = (Cmeas-X0*(Tcond-X5))/(1+ X1*(Tcond-X5)+X2*(Pcorr-X6)+X3*(Pcorr-X6)^2+X4*(Pcorr-X6)^3); Cmeas = C0+C1*C2*VR;",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "C0": "46.48405E-3",
        "C1": "152.28053",
        "C2": "1.0",
        "X0": "1.1667822E-3",
        "X1": "70.142356E-9",
        "X2": "1.8732E-6",
        "X3": "-776.89E-12",
        "X4": "148.9E-15",
        "X5": "15.001777",
        "X6": "10"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Conductivity Calibration Date          2020-12-09",
      "PREDEPLOYMENT_CALIB_DATE": "2020-12-02T00:00:00Z",
      "parameter_vendorinfo": {
        "vendor_schema": "None",
        "example": "Vendors can add their own parameter info here; they can add any field they like as a fieldname below parameter_vendorinfo"
      },
      "predeployment_vendorinfo": {
        "vendor_schema": "None",
        "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
      }
    },
    {
      "PARAMETER": "SDN:R03::TEMP_CNDC",
