=== euroargodev/sensor_metadata_json/schemas/argo.sensor.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "./argo.sensor.schema.json",
    "title": "JSON Schema for Argo Program Sensors",
    "description": "A JSON Schema used to populate Argo float sensor and parameter metadata elements.  See Argo User's Manual. Metada format Version 3.41.1",
    "format_version": { "const": "0.5.0" },
    "type": "object",
    "properties": {
        "sensor_info": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "date_creation": {
                    "type": "string",
                    "format": "date-time"
                },
                "link": {
                    "const" : "./argo.sensor.schema.json"
                },
                "format_version": {
                    "$ref": "#/format_version"
                },
                "contents": {
                    "type": "string"
                },
                "sensor_described": {
                    "type": "string"
                }
            },
            "required": [
                "created_by",
                "date_creation",
                "link",
                "format_version",
                "contents",
                "sensor_described"
            ]
        },
        "@context": {
            "type": "object",
            "properties": {
                "SDN:R03::": { "const": "http://vocab.nerc.ac.uk/collection/R03/current/" },
                "SDN:R25::": { "const": "http://vocab.nerc.ac.uk/collection/R25/current/" },
                "SDN:R26::": { "const": "http://vocab.nerc.ac.uk/collection/R26/current/" },
                "SDN:R27::": { "const": "http://vocab.nerc.ac.uk/collection/R27/current/" },
                "SDN:L22::": { "const": "http://vocab.nerc.ac.uk/collection/L22/current/" }
            },
            "required": [
                "SDN:R03::",
                "SDN:R25::",
                "SDN:R26::",
                "SDN:R27::"
            ],
            "additionalProperties": false
        },
        "SENSORS": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "SENSOR": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R25::",
                        "description": "SENSOR string must be valid in current Argo reference table R25",
                        "validation-uri" : "https://vocab.nerc.ac.uk/collection/R25/current/"
                    },
                    "SENSOR_MAKER": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R26::",
                        "description": "SENSOR_MAKER string must be valid in current Argo reference table R26",
                        "validation-uri": "https://vocab.nerc.ac.uk/collection/R26/current/"
                    },
                    "SENSOR_MODEL": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:(R27|L22)::",
                        "description": "SENSOR_MODEL string must be valid in current Argo reference table R27 or L22",
                        "validation-uri": "https://vocab.nerc.ac.uk/collection/R27/current/"
                    },
                    "SENSOR_FIRMWARE_VERSION": {
                        "type": "string",
                        "description": "Firmware version of this sensor_model, defined by the sensor_maker"
                    },
                    "SENSOR_SERIAL_NO": {
                        "type": "string",
                        "description": "Serial number of the sensor"
                    },
                    "sensor_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/sensor_vendorinfo"                        
                    }
                },
                "required": [
                    "SENSOR",
                    "SENSOR_MAKER",
                    "SENSOR_MODEL",
                    "SENSOR_SERIAL_NO",
                    "SENSOR_FIRMWARE_VERSION"
                ],
                "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "PARAMETERS": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "PARAMETER": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R03::",
                        "description": "PARAMETER string must be valid in current Argo reference table R03",
                        "validation_uri": "http://vocab.nerc.ac.uk/collection/R03/current/"
                    },
                    "PARAMETER_SENSOR": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R25::",
                        "description": "PARAMETER_SENSOR string must be valid in current Argo reference table R25 and must be listed as a SENSOR in the SENSORS section above",
                        "validation_uri": "http://vocab.nerc.ac.uk/collection/R25/current/"
                    },
                    "PARAMETER_UNITS": {
                        "type": "string"
                    },
                    "PARAMETER_ACCURACY": {
                        "type": "string"
                    },
                    "PARAMETER_RESOLUTION": {
                        "type": "string"
                    },
                    "PREDEPLOYMENT_CALIB_EQUATION": {
                        "type": "string",
                        "description" : "Calibration equation for this parameter."
                    },
                    "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                        "type": "object",
                        "description" : "Calibation coefficients are listed individually here, string-encoded to guarantee precision.  They will be compiled to create the Argo PREDEPLOYMENT_CALIB_COEFFCIENT string"
                    },
                    "PREDEPLOYMENT_CALIB_COMMENT": {
                        "type": "string"
                    },
                    "PREDEPLOYMENT_CALIB_DATE": {
                        "anyOf": [
                            {
                                "type": "string",
                                "format": "date-time"
                            },
                            {
                                "type": "string",
                                "const": " "
                            }
                        ]
                    },
                    "parameter_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/parameter_vendorinfo"
                    },
                    "predeployment_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/predeployment_vendorinfo"
                    }
                },
                "required": [
                    "PARAMETER",
                    "PARAMETER_SENSOR",
                    "PARAMETER_UNITS",
                    "PARAMETER_ACCURACY",
                    "PARAMETER_RESOLUTION",
                    "PREDEPLOYMENT_CALIB_EQUATION",
                    "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST",
                    "PREDEPLOYMENT_CALIB_COMMENT",
                    "PREDEPLOYMENT_CALIB_DATE"
                ],
                "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "instrument_vendorinfo": {
            "$ref" : "./argo.vendors.schema.json#/$defs/instrument_vendorinfo"
        }
    },
    "required": [
        "@context",
        "sensor_info",
        "SENSORS",
        "PARAMETERS"
    ],
    "uniqueItems": true,
    "additionalProperties": false

}

=== euroargodev/sensor_metadata_json/json_sensors/sensor-WETLABS-ECO_FLBBCDRT2K-8690.json
{
  "sensor_info": {
    "created_by": "FLBBCDRT2K-8690_JSON1.xlsm SBS-WriteArgoSensor() V0.1 (JCR)",
    "date_creation": "2024-02-08T17:08:40.000Z",
    "link": "./argo.sensor.schema.json",
    "format_version": "0.5.0",
    "contents": "JSON description of Sea-Bird Scientific ECO sensor FLBBCDRT2K-8690",
    "sensor_described": "FLBBCDRT2K-8690"
  },
  "@context": {
    "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
    "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
    "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
    "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/"
  },
  "instrument_vendorinfo": {
    "vendor_schema": "SBE",
    "version": "0.2",
    "SBE_part_number": "FAA-538092"
  },
  "SENSORS": [
    {
      "SENSOR": "SDN:R25::FLUOROMETER_CHLA",
      "SENSOR_MAKER": "SDN:R26::WETLABS",
      "SENSOR_MODEL": "SDN:R27::ECO_FLBBCD",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "8690",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
        "CONFIG_EcoChlaFluorescenceExcitationWavelength_nm": 470,
        "CONFIG_EcoChlaFluorescenceExcitationBandwidth_nm": 23,
        "CONFIG_EcoChlaFluorescenceEmissionWavelength_nm": 695,
        "CONFIG_EcoChlaFluorescenceEmissionBandwidth_nm": 70
      }
    },
    {
      "SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
      "SENSOR_MAKER": "SDN:R26::WETLABS",
      "SENSOR_MODEL": "SDN:R27::ECO_FLBBCD",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "8690",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
        "CONFIG_EcoBetaWavelength_nm": 700,
        "CONFIG_EcoBetaBandwidth_nm": 25,
        "CONFIG_EcoBetaAngle_angularDeg": 124
      }
    },
    {
      "SENSOR": "SDN:R25::FLUOROMETER_CDOM",
      "SENSOR_MAKER": "SDN:R26::WETLABS",
      "SENSOR_MODEL": "SDN:R27::ECO_FLBBCD",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "8690",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
        "CONFIG_EcoCdomFluorescenceExcitationWavelength_nm": 370,
        "CONFIG_EcoCdomFluorescenceExcitationBandwidth_nm": 15,
        "CONFIG_EcoCdomFluorescenceEmissionWavelength_nm": 460,
        "CONFIG_EcoCdomFluorescenceEmissionBandwidth_nm": 120
      }
    }
  ],
  "PARAMETERS": [
    {
      "PARAMETER": "SDN:R03::FLUORESCENCE_CHLA",
      "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA",
      "PARAMETER_UNITS": "count",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": " ",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated chlorophyll-a fluorescence measurement",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-30T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::BETA_BACKSCATTERING700",
      "PARAMETER_SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
      "PARAMETER_UNITS": "count",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": " ",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated backscattering measurement",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-30T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::FLUORESCENCE_CDOM",
      "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CDOM",
      "PARAMETER_UNITS": "count",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": " ",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated fluorescence from coloured dissolved organic matter sensor",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-30T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::CHLA",
      "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA",
      "PARAMETER_UNITS": "mg/m3",
      "PARAMETER_ACCURACY": "0.08 mg/m3",
      "PARAMETER_RESOLUTION": "0.025 mg/m3",
      "PREDEPLOYMENT_CALIB_EQUATION": "CHLA = (FLUORESCENCE_CHLA - DARK_CHLA) * SCALE_CHLA",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "SCALE_CHLA": "0.0073",
        "DARK_CHLA": "50"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "SBS Factory Calbration, 2024-01-30",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-30T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::BBP700",
      "PARAMETER_SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
      "PARAMETER_UNITS": "m-1",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": "BBP700=2*pi*khi*((BETA_BACKSCATTERING700-DARK_BACKSCATTERING700)*SCALE_BACKSCATTERING700-BETASW700)",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "DARK_BACKSCATTERING700": "48",
        "SCALE_BACKSCATTERING700": "1.855e-06",
        "khi": "1.076",
        "BETASW700": "(contribution of pure sea water) is calculated at 124 angularDeg"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "SBS Factory Calbration, 2024-01-30",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-30T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::CDOM",
      "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CDOM",
      "PARAMETER_UNITS": "ppb",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": "CDOM = (FLUORESCENCE_CDOM - DARK_CDOM) * SCALE_CDOM",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "SCALE_CDOM": "9.334e-02",
        "DARK_CDOM": "51"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "SBS Factory Calbration, 2024-01-30",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-30T00:00:00Z"
    }
  ]
}

=== euroargodev/sensor_metadata_json/json_sensors/sensor-AANDERAA-AANDERAA_OPTODE_4330-3901.json
{
  "sensor_info": {
    "created_by": "BAK test",
    "date_creation": "2023-02-03T07:38:07Z",
    "link" : "./argo.sensor.schema.json",
    "format_version": "0.5.0",
    "contents": "json file to describe a sensor for Argo. v0.4.0 draft",
    "sensor_described": "AANDERAA-AANDERAA_OPTODE_4330-3901"
  },
  "@context": {
    "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
    "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
    "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
    "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/"
  },
"SENSORS": [
    {
      "SENSOR": "SDN:R25::OPTODE_DOXY",
      "SENSOR_MAKER": "SDN:R26::AANDERAA",
      "SENSOR_MODEL": "SDN:R27::AANDERAA_OPTODE_4330",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "3901"
    }
  ],
  "PARAMETERS": [
    {
      "PARAMETER": "SDN:R03::C1PHASE_DOXY",
      "PARAMETER_SENSOR": "SDN:R25::OPTODE_DOXY",
      "PARAMETER_UNITS": "degree",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": "none",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  },
      "PREDEPLOYMENT_CALIB_COMMENT": "Phase measurement with blue excitation light; see TD269 Operating manual oxygen optode 4330, 4835, 483",
      "PREDEPLOYMENT_CALIB_DATE": " "
    },
    {
      "PARAMETER": "SDN:R03::C2PHASE_DOXY",
      "PARAMETER_SENSOR": "SDN:R25::OPTODE_DOXY",
      "PARAMETER_UNITS": "degree",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": "none",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { },
      "PREDEPLOYMENT_CALIB_COMMENT": "Phase measurement with red excitation light; see TD269 Operating manual oxygen optode 4330, 4835, 4831",
      "PREDEPLOYMENT_CALIB_DATE": " "    
    },
    {
      "PARAMETER": "SDN:R03::TEMP_DOXY",
      "PARAMETER_SENSOR": "SDN:R25::OPTODE_DOXY",
      "PARAMETER_UNITS": "degC",
      "PARAMETER_ACCURACY": "0.03",
      "PARAMETER_RESOLUTION": "0.01",
      "PREDEPLOYMENT_CALIB_EQUATION": "TEMP_DOXY=T0+T1*TEMP_VOLTAGE_DOXY+T2*TEMP_VOLTAGE_DOXY^2+T3*TEMP_VOLTAGE_DOXY^3+T4*TEMP_VOLTAGE_DOXY^4+T5*TEMP_VOLTAGE_DOXY^5; with TEMP_VOLTAGE_DOXY=voltage from thermistor bridge (mV)",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "T0": "not available",
        "T1": "not available",
        "T2": "not available",
        "T3": "not available",
        "T4": "not available",
        "T5": "not available"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "optode temperature, see TD269 Operating manual oxygen optode 4330, 4835, 4831",
      "PREDEPLOYMENT_CALIB_DATE": "2020-01-01T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::DOXY",
      "PARAMETER_SENSOR": "SDN:R25::OPTODE_DOXY",
      "PARAMETER_UNITS": "umol/kg",
      "PARAMETER_ACCURACY": "8 umol/kg or 10%",
      "PARAMETER_RESOLUTION": "1 umol/kg",
      "PREDEPLOYMENT_CALIB_EQUATION": "TPHASE_DOXY=C1PHASE_DOXY-C2PHASE_DOXY; Phase_Pcorr=TPHASE_DOXY+Pcoef1*PRES/1000; CalPhase=PhaseCoef0+PhaseCoef1*Phase_Pcorr+PhaseCoef2*Phase_Pcorr^2+PhaseCoef3*Phase_Pcorr^3; MOLAR_DOXY=[((c3+c4*TEMP_DOXY)/(c5+c6*CalPhase))-1]/Ksv; Ksv=c0+c1*TEMP_DOXY+c2*TEMP_DOXY^2; O2=MOLAR_DOXY*Scorr*Pcorr; Scorr=A*exp[PSAL*(B0+B1*Ts+B2*Ts^2+B3*Ts^3)+C0*PSAL^2]; A=[(1013.25-pH2O(TEMP,Spreset))/(1013.25-pH2O(TEMP,PSAL))]; pH2O(TEMP,S)=1013.25*exp[D0+D1*(100/(TEMP+273.15))+D2*ln((TEMP+273.15)/100)+D3*S]; Pcorr=1+((Pcoef2*TEMP+Pcoef3)*PRES)/1000; Ts=ln[(298.15-TEMP)/(273.15+TEMP)]; DOXY=O2/rho, where rho is the potential density [kg/L] calculated from CTD data",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "Spreset": "0",
        "Pcoef1": "0.1",
        "Pcoef2": "0.00022",
        "Pcoef3": "0.0419",
        "B0": "0.00624523",
        "B1": "-0.00737614",
        "B2": "-0.010341",
        "B3": "-0.00817083",
        "C0": "3.1201642E-3",
        "PhaseCoef0": "-1.652",
        "PhaseCoef1": "1",
        "PhaseCoef2": "0",
        "PhaseCoef3": "0",
        "c0": "0.00261275",
        "c1": "0.00011268",
        "c2": "2.2309e-06",
        "c3": "200.183",
        "c4": "-0.223497",
        "c5": "-43.6776",
        "c6": "4.10578",
        "D0": "24.4543",
        "D1": "-67.4509",
        "D2": "-4.8489",
        "D3": "-0.000544",
        "C1": "-285.56594E-6",
        "C2": "316.32993E-9",
        "C3": "-1.0767272E-6"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "see TD269 Operating manual oxygen optode 4330, 4835, 4831; see Processing Argo OXYGEN data at the DAC level, Version 2.2 (DOI: http://dx.doi.org/10.13155/39795)",
      "PREDEPLOYMENT_CALIB_DATE": "2020-01-01T00:00:00Z",
      "parameter_vendorinfo": {
        "example": "Vendors can add their own parameter info here; they can add any field they like as a fieldname below parameter_vendorinfo"
      },
      "predeployment_vendorinfo": {
        "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
      }
    },
    {
      "PARAMETER": "SDN:R03::PPOX_DOXY",
      "PARAMETER_SENSOR": "SDN:R25::OPTODE_DOXY",
      "PARAMETER_UNITS": "mbar",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": "TPHASE_DOXY=C1PHASE_DOXY-C2PHASE_DOXY; Phase_Pcorr=TPHASE_DOXY+Pcoef1*PRES/1000; CalPhase=PhaseCoef0+PhaseCoef1*Phase_Pcorr+PhaseCoef2*Phase_Pcorr^2+PhaseCoef3*Phase_Pcorr^3; Ksv=c0+c1*TEMP_DOXY+c2*TEMP_DOXY^2; MOLAR_DOXY=[((c3+c4*TEMP_DOXY)/(c5+c6*CalPhase))-1]/Ksv; Pcorr=1+((Pcoef2*TEMP+Pcoef3)*PRES)/1000; MOLAR_DOXY=MOLAR_DOXY*Pcorr; pH2Osat=1013.25*exp[D0+D1*(100/(TEMP+273.15))+D2*ln((TEMP+273.15)/100)]; Tcorr=44.6596*exp[2.00907+3.22014*Ts+4.05010*Ts^2+4.94457*Ts^3-2.56847e-1*Ts^4+3.88767*Ts^5]; Ts=ln[(298.15-TEMP)/(273.15+TEMP)]; PPOX_DOXY=MOLAR_DOXY*(0.20946*(1013.25-pH2Osat))/Tcorr*exp[0.317*PRES/(8.314*(TEMP+273.15))]",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "Pcoef1": "0.1",
        "Pcoef2": "0.00022",
        "Pcoef3": "0.0419",
        "PhaseCoef0": "-1.652",
        "PhaseCoef1": "1",
        "PhaseCoef2": "0",
        "PhaseCoef3": "0",
        "c0": "0.00261275",
        "c1": "0.00011268",
        "c2": "2.2309e-06",
        "c3": "200.183",
        "c4": "-0.223497",
        "c5": "-43.6776",
        "c6": "4.10578",
        "D0": "24.4543",
        "D1": "-67.4509",
        "D2": "-4.8489",
        "C0": "3.1201642E-3",
        "C1": "-285.56594E-6",
        "C2": "316.32993E-9",
        "C3": "-1.0767272E-6"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "see TD269 Operating manual oxygen optode 4330, 4835, 4831; see Processing Argo OXYGEN data at the DAC level, Version 2.2 (DOI: http://dx.doi.org/10.13155/39795)",
      "PREDEPLOYMENT_CALIB_DATE": "2020-01-01T00:00:00Z",
      "parameter_vendorinfo": {
        "example": "Vendors can add their own parameter info here; they can add any field they like as a fieldname below parameter_vendorinfo"
      },
      "predeployment_vendorinfo": {
        "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
      }
    }
  ],
  "instrument_vendorinfo": {
    "example": "Vendors can add something about the whole instrument here; they can add field they like as a fieldname below instrument_vendorinfo"
  }
}

=== euroargodev/sensor_metadata_json/json_sensors/sensor-WETLABS-ECO_FLBBFLRT2K-8660.json
{
  "sensor_info": {
    "created_by": "FLBBFLRT2K-8660.xls SBS-WriteArgoSensor() V0.1 (RDS)",
    "date_creation": "2024-02-08T20:59:35.000Z",
    "link": "./argo.sensor.schema.json",
    "format_version": "0.5.0",
    "contents": "JSON description of Sea-Bird Scientific ECO sensor FLBBFLRT2K-8660",
    "sensor_described": "FLBBFLRT2K-8660"
  },
  "@context": {
    "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
    "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
    "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
    "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/"
  },
  "instrument_vendorinfo": {
    "vendor_schema": "SBE",
    "version": "0.2",
    "SBE_part_number": "FAA-538092"
  },
  "SENSORS": [
    {
      "SENSOR": "SDN:R25::FLUOROMETER_CHLA",
      "SENSOR_MAKER": "SDN:R26::WETLABS",
      "SENSOR_MODEL": "SDN:R27::ECO_FLBBFL",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "8660",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
        "CONFIG_EcoChlaFluorescenceExcitationWavelength_nm": 470,
        "CONFIG_EcoChlaFluorescenceExcitationBandwidth_nm": 23,
        "CONFIG_EcoChlaFluorescenceEmissionWavelength_nm": 695,
        "CONFIG_EcoChlaFluorescenceEmissionBandwidth_nm": 70
      }
    },
    {
      "SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
      "SENSOR_MAKER": "SDN:R26::WETLABS",
      "SENSOR_MODEL": "SDN:R27::ECO_FLBBFL",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "8660",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
        "CONFIG_EcoBetaWavelength_nm": 700,
        "CONFIG_EcoBetaBandwidth_nm": 25,
        "CONFIG_EcoBetaAngle_angularDeg": 124
      }
    },
    {
      "SENSOR": "SDN:R25::FLUOROMETER_CHLA435",
      "SENSOR_MAKER": "SDN:R26::WETLABS",
      "SENSOR_MODEL": "SDN:R27::ECO_FLBBFL",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "8660",
      "sensor_vendorinfo": {
        "vendor_schema": "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
        "CONFIG_EcoChlaFluorescenceExcitationWavelength_nm": 435,
        "CONFIG_EcoChlaFluorescenceExcitationBandwidth_nm": 24,
        "CONFIG_EcoChlaFluorescenceEmissionWavelength_nm": 695,
        "CONFIG_EcoChlaFluorescenceEmissionBandwidth_nm": 70
      }
    }
  ],
  "PARAMETERS": [
    {
      "PARAMETER": "SDN:R03::FLUORESCENCE_CHLA",
      "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA",
      "PARAMETER_UNITS": "count",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": " ",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated chlorophyll-a fluorescence measurement",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-19T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::BETA_BACKSCATTERING700",
      "PARAMETER_SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
      "PARAMETER_UNITS": "count",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": " ",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated backscattering measurement",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-19T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::FLUORESCENCE_CHLA435",
      "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA435",
      "PARAMETER_UNITS": "count",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": " ",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated fluorescence from coloured dissolved organic matter sensor",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-19T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::CHLA",
      "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA",
      "PARAMETER_UNITS": "mg/m3",
      "PARAMETER_ACCURACY": "0.08 mg/m3",
      "PARAMETER_RESOLUTION": "0.025 mg/m3",
      "PREDEPLOYMENT_CALIB_EQUATION": "CHLA = (FLUORESCENCE_CHLA - DARK_CHLA) * SCALE_CHLA",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "SCALE_CHLA": "7.26e-03",
        "DARK_CHLA": "46"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "SBS Factory Calbration, 2024-01-19",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-19T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::BBP700",
      "PARAMETER_SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
      "PARAMETER_UNITS": "m-1",
      "PARAMETER_ACCURACY": " ",
      "PARAMETER_RESOLUTION": " ",
      "PREDEPLOYMENT_CALIB_EQUATION": "BBP700=2*pi*khi*((BETA_BACKSCATTERING700-DARK_BACKSCATTERING700)*SCALE_BACKSCATTERING700-BETASW700)",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "DARK_BACKSCATTERING700": "49",
        "SCALE_BACKSCATTERING700": "1.774e-06",
        "khi": "1.076",
        "BETASW700": "(contribution of pure sea water) is calculated at 124 angularDeg"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "SBS Factory Calbration, 2024-01-19",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-19T00:00:00Z"
    },
    {
      "PARAMETER": "SDN:R03::CHLA435",
      "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA435",
      "PARAMETER_UNITS": "mg/m3",
      "PARAMETER_ACCURACY": "0.08 mg/m3",
      "PARAMETER_RESOLUTION": "0.025 mg/m3",
      "PREDEPLOYMENT_CALIB_EQUATION": "CHLA435 = (FLUORESCENCE_CHLA435 - DARK_CHLA435) * SCALE_CHLA435",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "SCALE_CHLA435": "7.25e-03",
        "DARK_CHLA435": "42"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "SBS Factory Calbration, 2024-01-19",
      "PREDEPLOYMENT_CALIB_DATE": "2024-01-19T00:00:00Z"
    }
  ]
}
