=== euroargodev/sensor_metadata_json/schemas/argo.sensor.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "./argo.sensor.schema.json",
    "title": "JSON Schema for Argo Program Sensors",
    "description": "A JSON Schema used to populate Argo float sensor and parameter metadata elements.  See Argo User's Manual. Metada format Version 3.41.1",
    "format_version": { "const": "0.5.0" },
    "type": "object",
    "properties": {
        "sensor_info": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "date_creation": {
                    "type": "string",
                    "format": "date-time"
                },
                "link": {
                    "const" : "./argo.sensor.schema.json"
                },
                "format_version": {
                    "$ref": "#/format_version"
                },
                "contents": {
                    "type": "string"
                },
                "sensor_described": {
                    "type": "string"
                }
            },
            "required": [
                "created_by",
                "date_creation",
                "link",
                "format_version",
                "contents",
                "sensor_described"
            ]
        },
        "@context": {
            "type": "object",
            "properties": {
                "SDN:R03::": { "const": "http://vocab.nerc.ac.uk/collection/R03/current/" },
                "SDN:R25::": { "const": "http://vocab.nerc.ac.uk/collection/R25/current/" },
                "SDN:R26::": { "const": "http://vocab.nerc.ac.uk/collection/R26/current/" },
                "SDN:R27::": { "const": "http://vocab.nerc.ac.uk/collection/R27/current/" },
                "SDN:L22::": { "const": "http://vocab.nerc.ac.uk/collection/L22/current/" }
            },
            "required": [
                "SDN:R03::",
                "SDN:R25::",
                "SDN:R26::",
                "SDN:R27::"
            ],
            "additionalProperties": false
        },
        "SENSORS": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "SENSOR": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R25::",
                        "description": "SENSOR string must be valid in current Argo reference table R25",
                        "validation-uri" : "https://vocab.nerc.ac.uk/collection/R25/current/"
                    },
                    "SENSOR_MAKER": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R26::",
                        "description": "SENSOR_MAKER string must be valid in current Argo reference table R26",
                        "validation-uri": "https://vocab.nerc.ac.uk/collection/R26/current/"
                    },
                    "SENSOR_MODEL": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:(R27|L22)::",
                        "description": "SENSOR_MODEL string must be valid in current Argo reference table R27 or L22",
                        "validation-uri": "https://vocab.nerc.ac.uk/collection/R27/current/"
                    },
                    "SENSOR_FIRMWARE_VERSION": {
                        "type": "string",
                        "description": "Firmware version of this sensor_model, defined by the sensor_maker"
                    },
                    "SENSOR_SERIAL_NO": {
                        "type": "string",
                        "description": "Serial number of the sensor"
                    },
                    "sensor_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/sensor_vendorinfo"                        
                    }
                },
                "required": [
                    "SENSOR",
                    "SENSOR_MAKER",
                    "SENSOR_MODEL",
                    "SENSOR_SERIAL_NO",
                    "SENSOR_FIRMWARE_VERSION"
                ],
                "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "PARAMETERS": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "PARAMETER": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R03::",
                        "description": "PARAMETER string must be valid in current Argo reference table R03",
                        "validation_uri": "http://vocab.nerc.ac.uk/collection/R03/current/"
                    },
                    "PARAMETER_SENSOR": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R25::",
                        "description": "PARAMETER_SENSOR string must be valid in current Argo reference table R25 and must be listed as a SENSOR in the SENSORS section above",
                        "validation_uri": "http://vocab.nerc.ac.uk/collection/R25/current/"
                    },
                    "PARAMETER_UNITS": {
                        "type": "string"
                    },
                    "PARAMETER_ACCURACY": {
                        "type": "string"
                    },
                    "PARAMETER_RESOLUTION": {
                        "type": "string"
                    },
                    "PREDEPLOYMENT_CALIB_EQUATION": {
                        "type": "string",
                        "description" : "Calibration equation for this parameter."
                    },
                    "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                        "type": "object",
                        "description" : "Calibation coefficients are listed individually here, string-encoded to guarantee precision.  They will be compiled to create the Argo PREDEPLOYMENT_CALIB_COEFFCIENT string"
                    },
                    "PREDEPLOYMENT_CALIB_COMMENT": {
                        "type": "string"
                    },
                    "PREDEPLOYMENT_CALIB_DATE": {
                        "anyOf": [
                            {
                                "type": "string",
                                "format": "date-time"
                            },
                            {
                                "type": "string",
                                "const": " "
                            }
                        ]
                    },
                    "parameter_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/parameter_vendorinfo"
                    },
                    "predeployment_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/predeployment_vendorinfo"
                    }
                },
                "required": [
                    "PARAMETER",
                    "PARAMETER_SENSOR",
                    "PARAMETER_UNITS",
                    "PARAMETER_ACCURACY",
                    "PARAMETER_RESOLUTION",
                    "PREDEPLOYMENT_CALIB_EQUATION",
                    "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST",
                    "PREDEPLOYMENT_CALIB_COMMENT",
                    "PREDEPLOYMENT_CALIB_DATE"
                ],
                "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "instrument_vendorinfo": {
            "$ref" : "./argo.vendors.schema.json#/$defs/instrument_vendorinfo"
        }
    },
    "required": [
        "@context",
        "sensor_info",
        "SENSORS",
        "PARAMETERS"
    ],
    "uniqueItems": true,
    "additionalProperties": false

}

=== euroargodev/sensor_metadata_json/examples/sensor-TRIOS-RAMSES_ACC-template.json
{
  "sensor_info": {
    "created_by": "BAK test",
    "date_creation": "2023-02-03T07:38:07Z",
    "link" : "./argo.sensor.schema.json",
    "format_version": "0.5.0",
    "contents": "json file to describe an Trios RAMSES Sensor on an Argo float for sensor schema vxx.xx.xx draft",
    "sensor_described": "AANDERAA-AANDERAA_OPTODE_4330-3901"
  },
  "@context": { 
    "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
    "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
    "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
    "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/",
    "SDN:L22::": "http://vocab.nerc.ac.uk/collection/L22/current/" 
  },
"SENSORS": [
    {
      "SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR",
      "SENSOR_MAKER": "SDN:R26::TRIOS",
      "SENSOR_MODEL": "SDN:L22::TOOL0775",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "1600040",
      "sensor_vendorinfo": {
        "vendor_schema": "TRIOS",
        "version": "0.1",
        "TRIOS_RAMSESType": "Float"
      } 
  }
  ],
  "PARAMETERS": [
    {
        "PARAMETER": "SDN:R03::RADIOMETER_DOWN_IRR_INTEGRATION_TIME",
        "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR",
        "PARAMETER_UNITS": "ms",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  },
        "PREDEPLOYMENT_CALIB_COMMENT": " ",
        "PREDEPLOYMENT_CALIB_DATE": " "
    },
    {
        "PARAMETER": "SDN:R03::RADIOMETER_DOWN_IRR_PRE_PRES",
        "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR",
        "PARAMETER_UNITS": "dbar",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  },
        "PREDEPLOYMENT_CALIB_COMMENT": " ",
        "PREDEPLOYMENT_CALIB_DATE": " "
      },
      {
        "PARAMETER": "SDN:R03::RADIOMETER_DOWN_IRR_POST_PRES",
        "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR",
        "PARAMETER_UNITS": "dbar",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  },
        "PREDEPLOYMENT_CALIB_COMMENT": " ",
        "PREDEPLOYMENT_CALIB_DATE": " "
      },
      {
        "PARAMETER": "SDN:R03::RADIOMETER_DOWN_IRR_PRE_INCLINATION",
        "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR",
        "PARAMETER_UNITS": "degree",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  },
        "PREDEPLOYMENT_CALIB_COMMENT": " ",
        "PREDEPLOYMENT_CALIB_DATE": " "
      },
      {
        "PARAMETER": "SDN:R03::RADIOMETER_DOWN_IRR_POST_INCLINATION",
        "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR",
        "PARAMETER_UNITS": "degree",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  },
        "PREDEPLOYMENT_CALIB_COMMENT": " ",
        "PREDEPLOYMENT_CALIB_DATE": " "
      },
      {
        "PARAMETER": "SDN:R03::RADIOMETER_DOWN_IRR_DARK_AVERAGE",
        "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR",
        "PARAMETER_UNITS": "count",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  },
        "PREDEPLOYMENT_CALIB_COMMENT": " ",
        "PREDEPLOYMENT_CALIB_DATE": " "
      },
      {
        "PARAMETER": "SDN:R03::RAW_DOWNWELLING_IRRADIANCE",
        "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR",
        "PARAMETER_UNITS": "count",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  
            "OPTICAL_WAVELENGTH" : "",
            "B0" : "",
            "B1" : "",
            "S" : "",
            "Sair" : ""
        },
        "PREDEPLOYMENT_CALIB_COMMENT": " ",
        "PREDEPLOYMENT_CALIB_DATE": " ",
        "parameter_vendorinfo": {
            "vendor_schema": "TRIOS",
            "version": "0.1",
            "TRIOS_calfile" : " "
          },
        "predeployment_vendorinfo": {
        "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
        }
    }
  ],
  "instrument_vendorinfo": {
    "example": "Vendors can add something about the whole instrument here; they can add field they like as a fieldname below instrument_vendorinfo"
  }
}

=== euroargodev/sensor_metadata_json/json_sensors/sensor-SATLANTIC-SATLANTIC_OCR504_ICSW-42139.json
{
    "sensor_info": {
        "created_by": "SBE-OCRcalToJSON.py",
        "date_creation": "2024-03-19T13:02:42+00:00",
        "link": "./argo.sensor.schema.json",
        "format_version": "0.5.0",
        "contents": "json file to describe an OCR-504 sensor for sensor schema v0.4.0 draft",
        "sensor_described": "SATLANTIC-SATLANTIC_OCR504_ICSW-42139"
    },
    "@context": {
        "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
        "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
        "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
        "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/"
    },
    "SENSORS": [
        {
            "SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR380",
            "SENSOR_MAKER": "SDN:R26::SATLANTIC",
            "SENSOR_MODEL": "SDN:R27::SATLANTIC_OCR504_ICSW",
            "SENSOR_FIRMWARE_VERSION": " ",
            "SENSOR_SERIAL_NO": "42139",
            "sensor_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "CONFIG_OcrDownIrrWavelength1_nm": 380,
                "CONFIG_OcrDownIrrBandwidth1_nm": 10
            }
        },
        {
            "SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR412",
            "SENSOR_MAKER": "SDN:R26::SATLANTIC",
            "SENSOR_MODEL": "SDN:R27::SATLANTIC_OCR504_ICSW",
            "SENSOR_FIRMWARE_VERSION": " ",
            "SENSOR_SERIAL_NO": "42139",
            "sensor_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "CONFIG_OcrDownIrrWavelength2_nm": 412,
                "CONFIG_OcrDownIrrBandwidth2_nm": 10
            }
        },
        {
            "SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR490",
            "SENSOR_MAKER": "SDN:R26::SATLANTIC",
            "SENSOR_MODEL": "SDN:R27::SATLANTIC_OCR504_ICSW",
            "SENSOR_FIRMWARE_VERSION": " ",
            "SENSOR_SERIAL_NO": "42139",
            "sensor_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "CONFIG_OcrDownIrrWavelength3_nm": 490,
                "CONFIG_OcrDownIrrBandwidth3_nm": 10
            }
        },
        {
            "SENSOR": "SDN:R25::RADIOMETER_PAR",
            "SENSOR_MAKER": "SDN:R26::SATLANTIC",
            "SENSOR_MODEL": "SDN:R27::SATLANTIC_OCR504_ICSW",
            "SENSOR_FIRMWARE_VERSION": " ",
            "SENSOR_SERIAL_NO": "42139",
            "sensor_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2"
            }
        }
    ],
    "PARAMETERS": [
        {
            "PARAMETER": "SDN:R03::RAW_DOWNWELLING_IRRADIANCE380",
            "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR380",
            "PARAMETER_UNITS": "count",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": "none",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {},
            "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated downwelling irradiance measurement at 380 nm",
            "PREDEPLOYMENT_CALIB_DATE": "2020-11-05T00:00:00+00:00"
        },
        {
            "PARAMETER": "SDN:R03::RAW_DOWNWELLING_IRRADIANCE412",
            "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR412",
            "PARAMETER_UNITS": "count",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": "none",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {},
            "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated downwelling irradiance measurement at 412 nm",
            "PREDEPLOYMENT_CALIB_DATE": "2020-11-05T00:00:00+00:00"
        },
        {
            "PARAMETER": "SDN:R03::RAW_DOWNWELLING_IRRADIANCE490",
            "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR490",
            "PARAMETER_UNITS": "count",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": "none",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {},
            "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated downwelling irradiance measurement at 490 nm",
            "PREDEPLOYMENT_CALIB_DATE": "2020-11-05T00:00:00+00:00"
        },
        {
            "PARAMETER": "SDN:R03::RAW_DOWNWELLING_PAR",
            "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_PAR",
            "PARAMETER_UNITS": "count",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": "none",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {},
            "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated downwelling PAR measurement",
            "PREDEPLOYMENT_CALIB_DATE": "2020-11-05T00:00:00+00:00"
        },
        {
            "PARAMETER": "SDN:R03::DOWN_IRRADIANCE380",
            "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR380",
            "PARAMETER_UNITS": "W/m^2/nm",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": "DOWN_IRRADIANCE380=0.01*A1_380*(RAW_DOWNWELLING_IRRADIANCE380-A0_380)*lm_380",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                "A0_380": "2148866299.2",
                "A1_380": "1.65350515411e-07",
                "lm_380": "1.161"
            },
            "PREDEPLOYMENT_CALIB_COMMENT": "Calibrated downwelling irradiance measurement at 380 nm",
            "PREDEPLOYMENT_CALIB_DATE": "2020-11-05T00:00:00+00:00",
            "parameter_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "SBE_calfile": "DI42139A.cal"
            }
        },
        {
            "PARAMETER": "SDN:R03::DOWN_IRRADIANCE412",
            "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR412",
            "PARAMETER_UNITS": "W/m^2/nm",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": "DOWN_IRRADIANCE412=0.01*A1_412*(RAW_DOWNWELLING_IRRADIANCE412-A0_412)*lm_412",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                "A0_412": "2147863376.5",
                "A1_412": "2.07212473306e-07",
                "lm_412": "1.368"
            },
            "PREDEPLOYMENT_CALIB_COMMENT": "Calibrated downwelling irradiance measurement at 412 nm",
            "PREDEPLOYMENT_CALIB_DATE": "2020-11-05T00:00:00+00:00",
            "parameter_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "SBE_calfile": "DI42139A.cal"
            }
        },
        {
            "PARAMETER": "SDN:R03::DOWN_IRRADIANCE490",
            "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_DOWN_IRR490",
            "PARAMETER_UNITS": "W/m^2/nm",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": "DOWN_IRRADIANCE490=0.01*A1_490*(RAW_DOWNWELLING_IRRADIANCE490-A0_490)*lm_490",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                "A0_490": "2147885131.7",
                "A1_490": "2.07969573327e-07",
                "lm_490": "1.365"
            },
            "PREDEPLOYMENT_CALIB_COMMENT": "Calibrated downwelling irradiance measurement at 490 nm",
            "PREDEPLOYMENT_CALIB_DATE": "2020-11-05T00:00:00+00:00",
            "parameter_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "SBE_calfile": "DI42139A.cal"
            }
        },
        {
            "PARAMETER": "SDN:R03::DOWNWELLING_PAR",
            "PARAMETER_SENSOR": "SDN:R25::RADIOMETER_PAR",
            "PARAMETER_UNITS": "microMoleQuanta/m^2/sec",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": "DOWNWELLING_PAR=0.01*A1_PAR*(RAW_DOWNWELLING_PAR-A0_PAR)*lm_PAR",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                "A0_PAR": "2148056913.0",
                "A1_PAR": "3.68763177832e-06",
                "lm_PAR": "1.359"
            },
            "PREDEPLOYMENT_CALIB_COMMENT": "Calibrated downwelling PAR measurement",
            "PREDEPLOYMENT_CALIB_DATE": "2020-11-05T00:00:00+00:00",
            "parameter_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "SBE_calfile": "DI42139A.cal"
            }
        }
    ]
}

=== euroargodev/sensor_metadata_json/examples/sensor-WETLABS-MCOMS_FLBBCD-template_V0.3.0.json
{
    "sensor_info": {
      "created_by": "ECR test",
      "date_creation": "2023-04-10T07:38:07-07:00",
      "link" : "./argo.sensor.schema.json",
      "format_version": "0.5.0",
      "contents": "json file to describe an MCOMS sensor for sensor schema v0.4.0 draft",
      "sensor_described": "WETLABS-MCOMS_FLBBCD-0157"
    },
    "@context": {
      "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
      "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
      "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
      "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/"
    },
    "SENSORS": [
      {
        "SENSOR": "SDN:R25::FLUOROMETER_CHLA",
        "SENSOR_MAKER": "SDN:R26::WETLABS",
        "SENSOR_MODEL": "SDN:R27::MCOMS_FLBBCD",
        "SENSOR_FIRMWARE_VERSION": "MCOMS 5.45",
        "SENSOR_SERIAL_NO": "0157",
        "sensor_vendorinfo": {
          "vendor_schema": "SBE",
          "version": "0.2",
          "SBE_manufacturing_date": "2020-01-01T00:00:00Z",
          "CONFIG_EcoChlaFluorescenceExcitationWavelength_nm": 470,
          "CONFIG_EcoChlaFluorescenceExcitationBandwidth_nm": 23,
          "CONFIG_EcoChlaFluorescenceEmissionWavelength_nm": 695,
          "CONFIG_EcoChlaFluorescenceEmissionBandwidth_nm": 70
        } 
      },
      {
        "SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
        "SENSOR_MAKER": "SDN:R26::WETLABS",
        "SENSOR_MODEL": "SDN:R27::MCOMS_FLBBCD",
        "SENSOR_FIRMWARE_VERSION": "MCOMS 5.45",
        "SENSOR_SERIAL_NO": "0157",
        "sensor_vendorinfo": {
          "vendor_schema": "SBE",
          "version": "0.2",
          "SBE_manufacturing_date": "2020-01-01T00:00:00Z",
          "CONFIG_EcoBetaWavelength_nm": 700,
          "CONFIG_EcoBetaBandwidth_nm": 25,
          "CONFIG_EcoBetaAngle_angularDeg": 150
        }
      },
      {
        "SENSOR": "SDN:R25::FLUOROMETER_CDOM",
        "SENSOR_MAKER": "SDN:R26::WETLABS",
        "SENSOR_MODEL": "SDN:R27::MCOMS_FLBBCD",
        "SENSOR_FIRMWARE_VERSION": "MCOMS 5.45",
        "SENSOR_SERIAL_NO": "0157",
        "sensor_vendorinfo": {
          "vendor_schema": "SBE",
          "version": "0.2",
          "SBE_manufacturing_date": "2020-01-01T00:00:00Z",
          "CONFIG_EcoCdomFluorescenceExcitationWavelength_nm": 370,
          "CONFIG_EcoCdomFluorescenceExcitationBandwidth_nm": 15,
          "CONFIG_EcoCdomFluorescenceEmissionWavelength_nm": 460,
          "CONFIG_EcoCdomFluorescenceEmissionBandwidth_nm": 120
        }
      }
    ],
    "PARAMETERS": [
      {
        "PARAMETER": "SDN:R03::FLUORESCENCE_CHLA",
        "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA",
        "PARAMETER_UNITS": " ",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": " ",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { },
        "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated chlorophyll-a fluorescence measurement",
        "PREDEPLOYMENT_CALIB_DATE": "2021-03-31T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::BETA_BACKSCATTERING700",
        "PARAMETER_SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
        "PARAMETER_UNITS": " ",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": " ",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { },
        "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated backscattering measurement",
        "PREDEPLOYMENT_CALIB_DATE": "2021-03-31T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::FLUORESCENCE_CDOM",
        "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CDOM",
        "PARAMETER_UNITS": " ",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": " ",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { },
        "PREDEPLOYMENT_CALIB_COMMENT": "fluorescence from coloured dissolved organic matter",
        "PREDEPLOYMENT_CALIB_DATE": "2021-03-31T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::CHLA",
        "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA",
        "PARAMETER_UNITS": "mg/m3",
        "PARAMETER_ACCURACY": "0.08 mg/m3",
        "PARAMETER_RESOLUTION": "0.024 mg/m3",
        "PREDEPLOYMENT_CALIB_EQUATION": "CHLA = (FLUORESCENCE_CHLA - DARK_CHLA) * SCALE_CHLA",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { 
            "SCALE_CHLA":"1.891E-03",
            "DARK_CHLA":"51"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "SBS FACTORY CALIBRATION, 2018-09-25",
        "PREDEPLOYMENT_CALIB_DATE": "2018-09-25T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::BBP700",
        "PARAMETER_SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
        "PARAMETER_UNITS": "m-1",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": "4.67E-07",
        "PREDEPLOYMENT_CALIB_EQUATION": "BBP700=2*pi*khi*((BETA_BACKSCATTERING700-DARK_BACKSCATTERING700)*SCALE_BACKSCATTERING700-BETASW700)",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { 
            "DARK_BACKSCATTERING700" : "49",
            "SCALE_BACKSCATTERING700": "3.350E-07",
            "khi" : "1.142",
            "BETASW700" : "Contribution of pure sea water calculated at 150 angular deg"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "SBS FACTORY CALIBRATION, 2018-09-25",
        "PREDEPLOYMENT_CALIB_DATE": "2018-09-25T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::CDOM",
        "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CDOM",
        "PARAMETER_UNITS": "ppb",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": "1.28E-02",
        "PREDEPLOYMENT_CALIB_EQUATION": "CDOM = (FLUORESCENCE_CDOM - DARK_CDOM) * SCALE_CDOM",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { 
            "SCALE_CDOM":"6.336E-03",
            "DARK_CDOM":"51"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "SBS FACTORY CALIBRATION, 2018-09-25",
        "PREDEPLOYMENT_CALIB_DATE": "2018-09-25T00:00:00Z"
      }
    ]
}
