=== euroargodev/sensor_metadata_json/schemas/argo.sensor.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "./argo.sensor.schema.json",
    "title": "JSON Schema for Argo Program Sensors",
    "description": "A JSON Schema used to populate Argo float sensor and parameter metadata elements.  See Argo User's Manual. Metada format Version 3.41.1",
    "format_version": { "const": "0.5.0" },
    "type": "object",
    "properties": {
        "sensor_info": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "date_creation": {
                    "type": "string",
                    "format": "date-time"
                },
                "link": {
                    "const" : "./argo.sensor.schema.json"
                },
                "format_version": {
                    "$ref": "#/format_version"
                },
                "contents": {
                    "type": "string"
                },
                "sensor_described": {
                    "type": "string"
                }
            },
            "required": [
                "created_by",
                "date_creation",
                "link",
                "format_version",
                "contents",
                "sensor_described"
            ]
        },
        "@context": {
            "type": "object",
            "properties": {
                "SDN:R03::": { "const": "http://vocab.nerc.ac.uk/collection/R03/current/" },
                "SDN:R25::": { "const": "http://vocab.nerc.ac.uk/collection/R25/current/" },
                "SDN:R26::": { "const": "http://vocab.nerc.ac.uk/collection/R26/current/" },
                "SDN:R27::": { "const": "http://vocab.nerc.ac.uk/collection/R27/current/" },
                "SDN:L22::": { "const": "http://vocab.nerc.ac.uk/collection/L22/current/" }
            },
            "required": [
                "SDN:R03::",
                "SDN:R25::",
                "SDN:R26::",
                "SDN:R27::"
            ],
            "additionalProperties": false
        },
        "SENSORS": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "SENSOR": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R25::",
                        "description": "SENSOR string must be valid in current Argo reference table R25",
                        "validation-uri" : "https://vocab.nerc.ac.uk/collection/R25/current/"
                    },
                    "SENSOR_MAKER": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R26::",
                        "description": "SENSOR_MAKER string must be valid in current Argo reference table R26",
                        "validation-uri": "https://vocab.nerc.ac.uk/collection/R26/current/"
                    },
                    "SENSOR_MODEL": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:(R27|L22)::",
                        "description": "SENSOR_MODEL string must be valid in current Argo reference table R27 or L22",
                        "validation-uri": "https://vocab.nerc.ac.uk/collection/R27/current/"
                    },
                    "SENSOR_FIRMWARE_VERSION": {
                        "type": "string",
                        "description": "Firmware version of this sensor_model, defined by the sensor_maker"
                    },
                    "SENSOR_SERIAL_NO": {
                        "type": "string",
                        "description": "Serial number of the sensor"
                    },
                    "sensor_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/sensor_vendorinfo"                        
                    }
                },
                "required": [
                    "SENSOR",
                    "SENSOR_MAKER",
                    "SENSOR_MODEL",
                    "SENSOR_SERIAL_NO",
                    "SENSOR_FIRMWARE_VERSION"
                ],
                "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "PARAMETERS": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "PARAMETER": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R03::",
                        "description": "PARAMETER string must be valid in current Argo reference table R03",
                        "validation_uri": "http://vocab.nerc.ac.uk/collection/R03/current/"
                    },
                    "PARAMETER_SENSOR": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:R25::",
                        "description": "PARAMETER_SENSOR string must be valid in current Argo reference table R25 and must be listed as a SENSOR in the SENSORS section above",
                        "validation_uri": "http://vocab.nerc.ac.uk/collection/R25/current/"
                    },
                    "PARAMETER_UNITS": {
                        "type": "string"
                    },
                    "PARAMETER_ACCURACY": {
                        "type": "string"
                    },
                    "PARAMETER_RESOLUTION": {
                        "type": "string"
                    },
                    "PREDEPLOYMENT_CALIB_EQUATION": {
                        "type": "string",
                        "description" : "Calibration equation for this parameter."
                    },
                    "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                        "type": "object",
                        "description" : "Calibation coefficients are listed individually here, string-encoded to guarantee precision.  They will be compiled to create the Argo PREDEPLOYMENT_CALIB_COEFFCIENT string"
                    },
                    "PREDEPLOYMENT_CALIB_COMMENT": {
                        "type": "string"
                    },
                    "PREDEPLOYMENT_CALIB_DATE": {
                        "anyOf": [
                            {
                                "type": "string",
                                "format": "date-time"
                            },
                            {
                                "type": "string",
                                "const": " "
                            }
                        ]
                    },
                    "parameter_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/parameter_vendorinfo"
                    },
                    "predeployment_vendorinfo": {
                        "$ref" : "./argo.vendors.schema.json#/$defs/predeployment_vendorinfo"
                    }
                },
                "required": [
                    "PARAMETER",
                    "PARAMETER_SENSOR",
                    "PARAMETER_UNITS",
                    "PARAMETER_ACCURACY",
                    "PARAMETER_RESOLUTION",
                    "PREDEPLOYMENT_CALIB_EQUATION",
                    "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST",
                    "PREDEPLOYMENT_CALIB_COMMENT",
                    "PREDEPLOYMENT_CALIB_DATE"
                ],
                "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "instrument_vendorinfo": {
            "$ref" : "./argo.vendors.schema.json#/$defs/instrument_vendorinfo"
        }
    },
    "required": [
        "@context",
        "sensor_info",
        "SENSORS",
        "PARAMETERS"
    ],
    "uniqueItems": true,
    "additionalProperties": false

}

=== euroargodev/sensor_metadata_json/json_sensors/sensor-SBE-SEAFET-17682.json
{
    "sensor_info": {
        "created_by": "SBE ph_calsheet_creator.py",
        "date_creation": "2024-03-19T19:03:30+00:00",
        "link": "./argo.sensor.schema.json",
        "format_version": "0.5.0",
        "contents": "json file to describe an pH Sensor on an Argo float for sensor schema v0.4.0 draft",
        "sensor_described": "SBS-SEAFET-17682"
    },
    "@context": {
        "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
        "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
        "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
        "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/"
    },
    "SENSORS": [
        {
            "SENSOR": "SDN:R25::TRANSISTOR_PH",
            "SENSOR_MAKER": "SDN:R26::SBE",
            "SENSOR_MODEL": "SDN:R27::SEAFET",
            "SENSOR_FIRMWARE_VERSION": " ",
            "SENSOR_SERIAL_NO": "17682",
            "sensor_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "SBE_manufacturing_date": "2024-03-19T19:03:30.309466+00:00",
                "SBE_pHType": "Float",
                "SBE_ISFET_SERIAL_NO": "11764",
                "SBE_REFERENCE_SERIAL_NO": "11773"
            }
        }
    ],
    "PARAMETERS": [
        {
            "PARAMETER": "SDN:R03::VRS_PH",
            "PARAMETER_SENSOR": "SDN:R25::TRANSISTOR_PH",
            "PARAMETER_UNITS": "volt",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": " ",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {},
            "PREDEPLOYMENT_CALIB_COMMENT": "Voltage difference between reference and source from pH sensor (in volt",
            "PREDEPLOYMENT_CALIB_DATE": " "
        },
        {
            "PARAMETER": "SDN:R03::VK_PH",
            "PARAMETER_SENSOR": "SDN:R25::TRANSISTOR_PH",
            "PARAMETER_UNITS": "volt",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": " ",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {},
            "PREDEPLOYMENT_CALIB_COMMENT": "Counter electrode voltage of pH sensor (in volt)",
            "PREDEPLOYMENT_CALIB_DATE": " "
        },
        {
            "PARAMETER": "SDN:R03::IK_PH",
            "PARAMETER_SENSOR": "SDN:R25::TRANSISTOR_PH",
            "PARAMETER_UNITS": "nanoampere",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": " ",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {},
            "PREDEPLOYMENT_CALIB_COMMENT": "Counter electrode current of pH sensor (in nanoampere) ",
            "PREDEPLOYMENT_CALIB_DATE": " "
        },
        {
            "PARAMETER": "SDN:R03::IB_PH",
            "PARAMETER_SENSOR": "SDN:R25::TRANSISTOR_PH",
            "PARAMETER_UNITS": "nanoampere",
            "PARAMETER_ACCURACY": " ",
            "PARAMETER_RESOLUTION": " ",
            "PREDEPLOYMENT_CALIB_EQUATION": " ",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {},
            "PREDEPLOYMENT_CALIB_COMMENT": "Base current of pH sensor (in nanoampere)",
            "PREDEPLOYMENT_CALIB_DATE": " "
        },
        {
            "PARAMETER": "SDN:R03::PH_IN_SITU_FREE",
            "PARAMETER_SENSOR": "SDN:R25::TRANSISTOR_PH",
            "PARAMETER_UNITS": "dimensionless",
            "PARAMETER_ACCURACY": "0.005",
            "PARAMETER_RESOLUTION": "0.0004",
            "PREDEPLOYMENT_CALIB_EQUATION": "k0T=k0+k2*TEMP; pcorr=f1*PRES+f2*PRES^2+f3*PRES^3+f4*PRES^4+f5*PRES^5+f6*PRES^6; k0TP=k0T+pcorr; Tk=273.15+TEMP; Cltotal=(0.99889/35.453*PSAL/1.80655)/(1-0.001005*PSAL); ADH=3.4286e-6*TEMP^2+6.7524e-4*TEMP+0.49172143; IonS=19.924*PSAL/(1000-1.005*PSAL); log10gammaHCl=[-ADH*sqrt(IonS)/(1+1.394*sqrt(IonS))]+[(0.08885-0.000111*TEMP)*IonS]; deltaVHCl=17.85+0.1044*TEMP-0.001316*TEMP^2; log10gammaHCLtP=log10gammaHCl+[deltaVHCl*(PRES/10)/(R*Tk*ln(10))/2/10]; PH_IN_SITU_FREE=[(VRS_PH-k0TP)/(R*Tk/F*ln(10))]+[ln(Cltotal)/ln(10)]+2*log10gammaHCLtP-log10(1-0.001005*PSAL)",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                "fP_poly_order": "6",
                "f0": "-1.3189",
                "f1": "-8.453e-06",
                "f2": "6.5885e-08",
                "f3": "-1.1179e-10",
                "f4": "8.713e-14",
                "f5": "-3.2423e-17",
                "f6": "4.6608e-21",
                "K0": "-1.3219590000228736",
                "K2_poly_order": "3",
                "K2f0": "-0.00086825",
                "K2f1": "1.6881e-08",
                "K2f2": "-2.9158e-11",
                "K2f3": "8.6709e-15"
            },
            "PREDEPLOYMENT_CALIB_COMMENT": "",
            "PREDEPLOYMENT_CALIB_DATE": "2022-06-14T00:00:00+00:00",
            "predeployment_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "PREDEPLOYMENT_SEAFET_K0_CALIB_DATE": "2022-06-14T00:00:00+00:00",
                "PREDEPLOYMENT_SEAFET_K2_CALIB_DATE": "2022-06-02T00:00:00+00:00"
            }
        },
        {
            "PARAMETER": "SDN:R03::PH_IN_SITU_TOTAL",
            "PARAMETER_SENSOR": "SDN:R25::TRANSISTOR_PH",
            "PARAMETER_UNITS": "dimensionless",
            "PARAMETER_ACCURACY": "0.005",
            "PARAMETER_RESOLUTION": "0.0004",
            "PREDEPLOYMENT_CALIB_EQUATION": "k0T=k0+k2*TEMP; pcorr=f1*PRES+f2*PRES^2+f3*PRES^3+f4*PRES^4+f5*PRES^5+f6*PRES^6; k0TP=k0T+pcorr; Tk=273.15+TEMP; Cltotal=(0.99889/35.453*PSAL/1.80655)/(1-0.001005*PSAL); ADH=3.4286e-6*TEMP^2+6.7524e-4*TEMP+0.49172143; IonS=19.924*PSAL/(1000-1.005*PSAL); log10gammaHCl=[-ADH*sqrt(IonS)/(1+1.394*sqrt(IonS))]+[(0.08885-0.000111*TEMP)*IonS]; deltaVHCl=17.85+0.1044*TEMP-0.001316*TEMP^2; log10gammaHCLtP=log10gammaHCl+[deltaVHCl*(PRES/10)/(R*Tk*ln(10))/2/10]; PH_IN_SITU_FREE=[(VRS_PH-k0TP)/(R*Tk/F*ln(10))]+[ln(Cltotal)/ln(10)]+2*log10gammaHCLtP-log10(1-0.001005*PSAL)",
            "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                "fP_poly_order": "6",
                "f0": "-1.3189",
                "f1": "-8.453e-06",
                "f2": "6.5885e-08",
                "f3": "-1.1179e-10",
                "f4": "8.713e-14",
                "f5": "-3.2423e-17",
                "f6": "4.6608e-21",
                "K0": "-1.3219590000228736",
                "K2_poly_order": "3",
                "K2f0": "-0.00086825",
                "K2f1": "1.6881e-08",
                "K2f2": "-2.9158e-11",
                "K2f3": "8.6709e-15"
            },
            "PREDEPLOYMENT_CALIB_COMMENT": "",
            "PREDEPLOYMENT_CALIB_DATE": "2022-06-14T00:00:00+00:00",
            "predeployment_vendorinfo": {
                "vendor_schema": "SBE",
                "version": "0.2",
                "PREDEPLOYMENT_SEAFET_K0_CALIB_DATE": "2022-06-14T00:00:00+00:00",
                "PREDEPLOYMENT_SEAFET_K2_CALIB_DATE": "2022-06-02T00:00:00+00:00"
            }
        }
    ]
}

=== euroargodev/sensor_metadata_json/json_sensors/sensor-WETLABS-ECO_FLBBCD-3666.json
{
    "sensor_info": {
      "created_by": "ECR test",
      "date_creation": "2023-04-10T07:38:07-07:00",
      "link" : "./argo.sensor.schema.json",
      "format_version": "0.5.0",
      "contents": "json file to describe an ECO sensor FLBBCDREM-3666 on float WMOID 5906971 for sensor schema v0.4.0 draft",
      "sensor_described": "WETLABS-ECO_FLBBCD-3666"
    },
    "@context": {
      "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
      "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
      "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
      "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/"
    },
    "instrument_vendorinfo" : {
      "vendor_schema": "SBE",
      "version": "0.2",
      "SBE_part_number" : "FAA-538092"
    },
    "SENSORS": [
      {
        "SENSOR": "SDN:R25::FLUOROMETER_CHLA",
        "SENSOR_MAKER": "SDN:R26::WETLABS",
        "SENSOR_MODEL": "SDN:R27::ECO_FLBBCD",
        "SENSOR_FIRMWARE_VERSION": " ",
        "SENSOR_SERIAL_NO": "3666",
        "sensor_vendorinfo": {
          "vendor_schema": "SBE",
          "version": "0.2",
          "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
          "CONFIG_EcoChlaFluorescenceExcitationWavelength_nm": 470,
          "CONFIG_EcoChlaFluorescenceExcitationBandwidth_nm": 23,
          "CONFIG_EcoChlaFluorescenceEmissionWavelength_nm": 695,
          "CONFIG_EcoChlaFluorescenceEmissionBandwidth_nm": 70
        }
      },
      {
        "SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
        "SENSOR_MAKER": "SDN:R26::WETLABS",
        "SENSOR_MODEL": "SDN:R27::ECO_FLBBCD",
        "SENSOR_FIRMWARE_VERSION": " ",
        "SENSOR_SERIAL_NO": "3666",
        "sensor_vendorinfo": {
          "vendor_schema": "SBE",
          "version": "0.2",
          "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
          "CONFIG_EcoBetaWavelength_nm": 700,
          "CONFIG_EcoBetaBandwidth_nm": 25,
          "CONFIG_EcoBetaAngle_angularDeg": 124
        }
      },
      {
        "SENSOR": "SDN:R25::FLUOROMETER_CDOM",
        "SENSOR_MAKER": "SDN:R26::WETLABS",
        "SENSOR_MODEL": "SDN:R27::ECO_FLBBCD",
        "SENSOR_FIRMWARE_VERSION": " ",
        "SENSOR_SERIAL_NO": "3666",
        "sensor_vendorinfo": {
          "vendor_schema": "SBE",
          "version": "0.2",
          "SBE_manufacturing_date": "2014-07-17T00:00:00Z",
          "CONFIG_EcoCdomFluorescenceExcitationWavelength_nm": 370,
          "CONFIG_EcoCdomFluorescenceExcitationBandwidth_nm": 15,
          "CONFIG_EcoCdomFluorescenceEmissionWavelength_nm": 460,
          "CONFIG_EcoCdomFluorescenceEmissionBandwidth_nm": 120
        }
      }
    ],
    "PARAMETERS": [
      {
        "PARAMETER": "SDN:R03::FLUORESCENCE_CHLA",
        "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA",
        "PARAMETER_UNITS": "count",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": " ",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { },
        "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated chlorophyll-a fluorescence measurement",
        "PREDEPLOYMENT_CALIB_DATE": "2020-10-06T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::BETA_BACKSCATTERING700",
        "PARAMETER_SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
        "PARAMETER_UNITS": "count",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": " ",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { },
        "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated backscattering measurement",
        "PREDEPLOYMENT_CALIB_DATE": "2020-10-06T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::FLUORESCENCE_CDOM",
        "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CDOM",
        "PARAMETER_UNITS": "count",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": " ",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { },
        "PREDEPLOYMENT_CALIB_COMMENT": "Uncalibrated fluorescence from coloured dissolved organic matter sensor",
        "PREDEPLOYMENT_CALIB_DATE": "2020-10-06T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::CHLA",
        "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CHLA",
        "PARAMETER_UNITS": "mg/m3",
        "PARAMETER_ACCURACY": "0.08 mg/m3",
        "PARAMETER_RESOLUTION": "0.025 mg/m3",
        "PREDEPLOYMENT_CALIB_EQUATION": "CHLA = (FLUORESCENCE_CHLA - DARK_CHLA) * SCALE_CHLA",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { 
            "SCALE_CHLA": "0.0066",
            "DARK_CHLA": "44"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "SBS FACTORY CALIBRATION, 2018-09-25",
        "PREDEPLOYMENT_CALIB_DATE": "2018-09-25T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::BBP700",
        "PARAMETER_SENSOR": "SDN:R25::BACKSCATTERINGMETER_BBP700",
        "PARAMETER_UNITS": "m-1",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "BBP700=2*pi*khi*((BETA_BACKSCATTERING700-DARK_BACKSCATTERING700)*SCALE_BACKSCATTERING700-BETASW700)",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { 
            "DARK_BACKSCATTERING700" : "47",
            "SCALE_BACKSCATTERING700": "1.799e-06",
            "khi" : "1.076",
            "BETASW700" : "(contribution of pure sea water) is calculated at 124 angularDeg"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "Sullivan et al., 2012, Zhang et al., 2009, BETASW700 is the contribution by the pure seawater at 700nm, the calculation can be found at http://doi.org/10.17882/42916. Reprocessed from the file provided by Andrew Bernard (Seabird) following ADMT18. This file is accessible at http://doi.org/10.17882/54520",
        "PREDEPLOYMENT_CALIB_DATE": "2018-09-25T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:R03::CDOM",
        "PARAMETER_SENSOR": "SDN:R25::FLUOROMETER_CDOM",
        "PARAMETER_UNITS": "ppb",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "CDOM = (FLUORESCENCE_CDOM - DARK_CDOM) * SCALE_CDOM",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { 
            "SCALE_CDOM":"0.0814",
            "DARK_CDOM":"42"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "SBS FACTORY CALIBRATION, 2018-09-25",
        "PREDEPLOYMENT_CALIB_DATE": "2018-09-25T00:00:00Z"
      }
    ]
}

=== euroargodev/sensor_metadata_json/json_sensors/sensor-SBE-SBE41CP-11643.json
{
  "sensor_info": {
    "created_by": "BAK test",
    "date_creation": "2023-02-03T07:38:07Z",
    "link" : "./argo.sensor.schema.json",
    "format_version": "0.5.0",
    "contents": "json file to describe a sensor for Argo. v0.4.0 draft",
    "sensor_described": "SBE-SBE41CP-11643 on float 6904191"
  },
  "@context": {
    "SDN:R03::": "http://vocab.nerc.ac.uk/collection/R03/current/",
    "SDN:R25::": "http://vocab.nerc.ac.uk/collection/R25/current/",
    "SDN:R26::": "http://vocab.nerc.ac.uk/collection/R26/current/",
    "SDN:R27::": "http://vocab.nerc.ac.uk/collection/R27/current/"
  },
  "SENSORS": [
    {
      "SENSOR": "SDN:R25::CTD_PRES",
      "SENSOR_MAKER": "SDN:R26::DRUCK",
      "SENSOR_MODEL": "SDN:R27::DRUCK_2900PSIA",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "11076214",
      "sensor_vendorinfo": {
        "vendor_schema" : "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2022-01-01T00:00:00Z"
      }
    },
    {
      "SENSOR": "SDN:R25::CTD_TEMP",
      "SENSOR_MAKER": "SDN:R26::SBE",
      "SENSOR_MODEL": "SDN:R27::SBE41CP",
      "SENSOR_SERIAL_NO": "11643",
      "SENSOR_FIRMWARE_VERSION": " ",
      "sensor_vendorinfo": {
        "vendor_schema" : "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2022-01-01T00:00:00Z"
      }
    },
    {
      "SENSOR": "SDN:R25::CTD_CNDC",
      "SENSOR_MAKER": "SDN:R26::SBE",
      "SENSOR_MODEL": "SDN:R27::SBE41CP",
      "SENSOR_FIRMWARE_VERSION": " ",
      "SENSOR_SERIAL_NO": "11643",
      "sensor_vendorinfo": {
        "vendor_schema" : "SBE",
        "version": "0.2",
        "SBE_manufacturing_date": "2022-01-01T00:00:00Z"
      }
    }
  ],
  "PARAMETERS": [
    {
      "PARAMETER": "SDN:R03::PRES",
      "PARAMETER_SENSOR": "SDN:R25::CTD_PRES",
      "PARAMETER_UNITS": "decibar",
      "PARAMETER_ACCURACY": "2.4",
      "PARAMETER_RESOLUTION": "0.1",
      "PREDEPLOYMENT_CALIB_EQUATION": "y = thermistor_output; t = PTHA0 + PTHA1 * y + PTHA2 * y^2; x = pressure_output - PTCA0 - PTCA1 * t - PTCA2 * t^2; n = x * PTCB0 / (PTCB0 + PTCB1 * t + PTCB2 * t^2); pressure = PA0 + PA1 * n + PA2 * n^2;",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "PA0": " -1.860485e-001",
        "PA1": " 3.913091e-004",
        "PA2": "-2.833018e-013",
        "PTCA0": "6.794577e+003",
        "PTCA1": "-9.846636e+000",
        "PTCA2": "-6.839699e-001",
        "PTCB0": "3.203647e+005",
        "PTCB1": "2.935842e+001",
        "PTCB2": "-5.287902e-001",
        "PTHA0": "-8.015838e+001",
        "PTHA1": "4.998022e-002",
        "PTHA2": "-4.733751e-007"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Pressure Calibration Date              2021-03-31",
      "PREDEPLOYMENT_CALIB_DATE": "2021-03-31T00:00:00Z",
      "parameter_vendorinfo": {
        "vendor_schema" : "SBE",
        "version": "0.2"
      },
      "predeployment_vendorinfo": {
        "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
      }
    },
    {
      "PARAMETER": "SDN:R03::TEMP",
      "PARAMETER_SENSOR": "SDN:R25::CTD_TEMP",
      "PARAMETER_UNITS": "degree_Celsius",
      "PARAMETER_ACCURACY": "0.002",
      "PARAMETER_RESOLUTION": "0.001",
      "PREDEPLOYMENT_CALIB_EQUATION": "Temperature ITS-90 = 1/{a0 + a1[ln(n)] + a2[ln(n)^2] + a3[ln(n)^2]} - 273.15; n = instrument output;",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "a0": "-8.716632e-004",
        "a1": " 2.937892e-004",
        "a2": "-3.758125e-006",
        "a3": " 1.520066e-007"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Temperature Calibration Date 2021-03-31",
      "PREDEPLOYMENT_CALIB_DATE": "2021-03-31T00:00:00Z",
      "parameter_vendorinfo": {
        "vendor_schema": "None",
        "anyproperty_works_here" : "any content is valide if vendor_schema is None; if vendor_schema is specfied, content will be validated agains this subschemea",
        "example": "Vendors can add their own parameter info here; they can add any field they like as a fieldname below  parameter t_vendorinfo"
      }
    },
    {
      "PARAMETER": "SDN:R03::PSAL",
      "PARAMETER_SENSOR": "SDN:R25::CTD_CNDC",
      "PARAMETER_UNITS": "psu",
      "PARAMETER_ACCURACY": "0.005",
      "PARAMETER_RESOLUTION": "0.001",
      "PREDEPLOYMENT_CALIB_EQUATION": "f=INST_FREQ*sqrt(1.0+wBOTC*t)/1000.0;Conductivity=(g+h*f^2+i*f^3+j*f^4)/(1+delta*t+epsilon*p) Siemens/meter;t=temperature[degC];p=pressure[dbar];delta=CTcor;epsilon=CPcor;         ",
      "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
        "g": "-1.023943e+000",
        "h": " 1.465505e-001",
        "i": "-2.806563e-004",
        "j": " 4.044779e-005",
        "CPcor": "-9.5700e-008",
        "CTcor": "3.2500e-006",
        "WBOTC": " 3.1475e-008"
      },
      "PREDEPLOYMENT_CALIB_COMMENT": "Conductivity Calibration Date 2021-03-31",
      "PREDEPLOYMENT_CALIB_DATE": "2021-03-31T00:00:00Z",
      "predeployment_vendorinfo": {
        "vendor_schema": "SBE",
        "version" : "0.2"
      }
    }
  ],
  "instrument_vendorinfo": {
    "vendor_schema" : "SBE",
    "version" : "0.2"
  }
}
